account/urls.py
from django.urls import path
from . import views

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page="/account/login/"), name="logout"),
]

bookSearch/urls.py
from django.urls import path
from . import views


app_name = 'bookSearch'

urlpatterns = [
    path('', views.booksearch, name="booksearch"),
]

homepage/urls.py
from django.urls import path
from . import views


app_name = 'homepage'

urlpatterns = [
    path('', views.index, name="index"),
]

myProfile/urls.py
from django.urls import path
from . import views


app_name = 'myProfile'

urlpatterns = [
    path('', views.profile, name="profile"),
]

story6test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('profile/', include('myProfile.urls')),
    path('bookSearch/', include('bookSearch.urls')),
    path('account/', include('account.urls')),
]

account/models.py
from django.db import models

# Create your models here.

bookSearch/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models
import datetime

# Create your models here.

class response(models.Model):
    status = models.CharField(max_length=300)
    date = models.DateTimeField(auto_now_add=True, blank=True)

myProfile/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

from .models import response

class ResponseForm(forms.ModelForm):
    class Meta:
        model = response
        fields = [
            'status',
        ]

account/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout

# Create your views here.


def index(request):
    return render(request, 'account/index.html')

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account/login/')
    else:
        form = UserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'registration/register.html', context)

bookSearch/views.py
from django.shortcuts import render

# Create your views here.

def booksearch(request):
    return render(request, 'booksearch/index.html')

homepage/views.py
from django.shortcuts import render, redirect
from .forms import ResponseForm
from .models import response

# Create your views here.

def index(request):
    responses = response.objects.all()
    if request.method == "POST":
        form = ResponseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect ('/')
    
    else:
        form = ResponseForm()
    context = {
        'form' : form,
        'respon' : responses,
    }

    return render(request, 'homepage/index.html', context)

myProfile/views.py
from django.shortcuts import render

# Create your views here.

def profile(request):
    return render(request, 'myProfile/index.html')

bookSearch/templates/booksearch/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-theme="light">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Book Search</title>
    </head>
    {% with current_page='search'%}
    {% include 'navbar.html' %}
    {% endwith %}
    <body>
        <div class="row text-center mt-3">
            <div class="col-12">
                <h1>
                    Search Your Favourites Books
                </h1>
            </div>
            <div class="col-3">
            </div>
            <div class="col-6">
                <div class="input-group mb-3">
                    <input id="search" type="text" class="form-control" placeholder="Search.." aria-label="Recipient's username" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button id="button" class="btn btn-outline-secondary" type="button">Search</button>
                    </div>
                </div>
            </div>
            <div class="col-3">
            </div>
        </div>
        <div class="container">
            <table id = "results" class = "table table-striped table-light mt-3"></table>
        </div>


        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
        <script src="{% static 'js/booksearch.js' %}"></script>
    </body>
</html>

homepage/templates/homepage/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-theme="light">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>Landing Page</title>
    </head>
    {% with current_page='home'%}
    {% include 'navbar.html' %}
    {% endwith %}
    <body>
        <div class="row mt-5">
            <div class="col-6 text-center">
                <img class="rounded-circle img-thumbnail" src="{% static 'img/portrait.jpg' %}"" alt="">
            </div>
            <div class="col-6 text-center">
                {% if user.is_authenticated%}
                <h4 class="font-weight-bold">Hello {{user.username}},<br>what's up?</h4>
                {% else %}
                <h4 class="font-weight-bold">Hello,<br>what's up?</h4>
                {% endif %}
                <div class="container mt-3 mb-1">
                    <form action="{% url 'homepage:index' %}" method="post">
                        {% csrf_token %}
                        {% for item in form %}
                        {{item}}
                        {% endfor %}
                        <br>
                        <button type="submit" class="btn btn-outline-secondary mt-3" id="submit">Submit</button>
                    </form>
                </div>
            </div>
            {% for item in respon %}
            <div class="col-12">
                <div class="container">
                    <h4 class="text-break font-weight-bold mt-3 mb-3">{{item.status}}</h4>
                    <p>{{item.date}}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="{% static 'js/accordion.js'%}">
        </script>
    </body>
</html>

homepage/templates/navbar.html
{% load static %}
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="">Mind.</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item {% if current_page == 'home' %} active {% endif %}">
        <a class="nav-link" href="{% url 'homepage:index'%}">Home</a>
      </li>
      <li class="nav-item {% if current_page == 'profile' %} active {% endif %}">
        <a class="nav-link" href="{% url 'myProfile:profile'%}">Profile</a>
      </li>
      <li class="nav-item {% if current_page == 'search' %} active {% endif %}">
        <a class="nav-link" href="{% url 'bookSearch:booksearch'%}">Search</a>
      </li>
      <li class="nav-item {% if current_page == 'account' %} active {% endif %}">
        <a class="nav-link" href="{% url 'account:index'%}">Dashboard</a>
      </li>
      <li>
        <div class="toggle-container">
          <input type="checkbox" id="switch" name="theme" /><label id="switch_label" for="switch">Toggle</label>
        </div>
      </li>
    </ul>
  </div>
</nav>

myProfile/templates/myProfile/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" data-theme="light">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" type="text/css" href="{% static 'css/nav.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/progressBar.css' %}">
        <title>Landing Page</title>
    </head>
    {% with current_page='profile'%}
    {% include 'navbar.html' %}
    {% endwith %}
    <body>
        <div class="row mt-5 text-center">
            <div class="col-12">
                <div class="container">
                    <h1>Daril Nofriansyah Badruddin</h1>
                </div>
            </div>
        </div>
        <div class="container">
            <div id="accordion">
                <h3 class = "judul">
                    Biodata
                </h3>
                <div>
                    <p class="text-center">
                        I am an undergraduate IT student who likes to solve problem.
                        I am interested in obtaining new knowledge and skills, 
                        which I use to self-improve. I am a
                        creative person and a communicative person.
                    </p>
                </div>
                <h3 class = "judul">
                    Activity
                </h3>
                <div>
                    <ul>
                        <li>Badan Eksekutif Mahasiswa Fasilkom UI 2019</li>
                        <li>COMPFEST 12</li>
                        <li>Akademis</li>
                    </ul>
                </div>
                <h3>Skills</h3>
                <div>
                    <ul>
                        <li>Java Programming</li>
                        <li>Photoshop Basics</li>
                        <li>Mengeluh</li>
                    </ul>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="{% static 'js/accordion.js' %}"></script>
    </body>
</html>